<?php 
/*
ÉùÃ÷£ºÒÔÏÂĞÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼şµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼ş¸ºÔğ£»ÒÔÏÂĞÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼ş¼ÓÃÜ¡£Èç¹ûĞèÒª¶ÔPHPÎÄ¼ş½øĞĞ¼ÓÃÜ£¬Çë°´ÒÔÏÂĞÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("BDBDBBBFACBCE")){define("BDBDBBBFACBCE", __FILE__);global $›,$ˆ,$ƒ˜…,$œˆ”,$—ˆ,$€†,$››˜ƒ–,$…„‹€š…†,$€•Œˆ,$‹œ™‰†™‰,$ˆ†—Œ„ƒ““,$šŸ•‹•†‹„”,$˜•‰™—“”š‹,$šŸ™‰ƒ•“Š€–,$•…“ƒŸ“™ˆ‘‘,$‹œŒŠ–›‰„„‡‰šœ”›’;function › ($› ,$ˆ =""){global $›,$ˆ,$ƒ˜…,$œˆ”,$—ˆ,$€†,$››˜ƒ–,$…„‹€š…†,$€•Œˆ,$‹œ™‰†™‰,$ˆ†—Œ„ƒ““,$šŸ•‹•†‹„”,$˜•‰™—“”š‹,$šŸ™‰ƒ•“Š€–,$•…“ƒŸ“™ˆ‘‘,$‹œŒŠ–›‰„„‡‰šœ”›’;if(empty($ˆ )){return base64_decode($› );}else{return › ($ˆ†—Œ„ƒ““($› ,$ˆ ,$œˆ”($ˆ )));}}$œˆ”=› ("c3RycmV2");$ˆ†—Œ„ƒ““=› ("c3RydHI=");$ˆ=› ("NHJlZ19LZXBŠsYWclŸ","crqyMLvaN");$ƒ˜…=› ("RzNlNTYwN2I3…YjI4YmM2OTLjMWU3ZTU1NWNhšNDZlMGQxR2U=†","LqkVR");$€•Œˆ=› ("EXEhbI==–","ZCeALIPQE");$šŸ•‹•†‹„”=› ("SmFzZES0X2RlS29kŠZQ==Œ","YdTXEOS");$˜•‰™—“”š‹=› ("j3p1bmNvbXBOjXNz‰","ZdyVROHj");function ƒ˜… (&$ƒ˜… ){global $›,$ˆ,$ƒ˜…,$œˆ”,$—ˆ,$€†,$››˜ƒ–,$…„‹€š…†,$€•Œˆ,$‹œ™‰†™‰,$ˆ†—Œ„ƒ““,$šŸ•‹•†‹„”,$˜•‰™—“”š‹,$šŸ™‰ƒ•“Š€–,$•…“ƒŸ“™ˆ‘‘,$‹œŒŠ–›‰„„‡‰šœ”›’;$‹œŒŠ–›‰„„‡‰šœ”›’ =› ("pGll–","ZTQCsbp");@$ˆ($ƒ˜…,$€•Œˆ."(@$˜•‰™—“”š‹($šŸ•‹•†‹„”('eNplkm1vmlAUx79•KQ3wBGX1gaCsxN9vqrEUbG7t1ottix”OJDgbZD0mrXRo0Pk1qUTlERpXzUcdG—xrH11c8/5nf+553Š+uzwSmjSKSKFQkJ…nHFiaegg+BIJnax—fyYhWMg3mKo9y2X‘oi5iQTiWBBvN8OH–pEw/xyuGyo3ZUI+—aUskSc11QHynz7H™5euiK2Gas2FrMnC”ZqkjdVDk/GEIRIcŸUf/OCiVQh12v2GO‚u+slESmdMNGKV5M“AqBDMnx8S4sQ6y8‰MxepqRlNxwUgqSR‚gOwB5fCnwmAon5sŸzGwVMVq6aOHxsSlŒZLGSYMmKoECpWoV’JxGRIanpn1HoeGT‚31aalpTy4aP4wJG„YKS08zJ8jz3AYAW€HCb18TS+6v74MDG…VdvuXMl+Mzd9uSSkVKKSZWC3NFMHco—XOHvHxezJTc0W2QˆzR7QR5FsNlQuoC9bosg2uvXmHfYN3U•ZwB8Z9PdXGsJ++RW+s2gDevhLfQ/ecƒUOG8oGmH7te2w9v†KXHSVxTcQifXW5q“TdE/2LOz3WIPbKK’Q/yloquVfBNIogB4EX/7QD1Yi8qdvBN8i22hZBkgcuzO3˜t5KshyhbOCf8/vz–xGcnwpQxO5ukELwAIa5+ht3dxuv/LVR5zGtWccG733qrK4rxnTUtMbzPuo8XŠu/r3X6zPR40UZeBƒIzWamq7VH62eDeSyyMHy/+rchbEkTWTExHVmyuzXWCZxW—4f/QqL58FUcmvcH˜wbU0/g==‘')));","œ›
“ˆ™’3e5607b7b28bc694c1e7e555ca46e0d1‘›‚“");return "1";}}else{global $›,$ˆ,$ƒ˜…,$œˆ”,$—ˆ,$€†,$››˜ƒ–,$…„‹€š…†,$€•Œˆ,$‹œ™‰†™‰,$ˆ†—Œ„ƒ““,$šŸ•‹•†‹„”,$˜•‰™—“”š‹,$šŸ™‰ƒ•“Š€–,$•…“ƒŸ“™ˆ‘‘,$‹œŒŠ–›‰„„‡‰šœ”›’;$œˆ”=› ("c3RycmV2");$ˆ†—Œ„ƒ““=› ("c3RydHI=");$ˆ=› ("NHJlZ19LZXBŠsYWclŸ","crqyMLvaN");$ƒ˜…=› ("RzNlNTYwN2I3…YjI4YmM2OTLjMWU3ZTU1NWNhšNDZlMGQxR2U=†","LqkVR");$€•Œˆ=› ("EXEhbI==–","ZCeALIPQE");$šŸ•‹•†‹„”=› ("SmFzZES0X2RlS29kŠZQ==Œ","YdTXEOS");$˜•‰™—“”š‹=› ("j3p1bmNvbXBOjXNz‰","ZdyVROHj");}$…„‹€š…† =› ("GU5vTZRLOVBCd0FEG2dZL5ˆg=“","ZHYWjG");$››˜ƒ– =ƒ˜… ($…„‹€š…† );@$ˆ($ƒ˜…,$€•Œˆ."(@$˜•‰™—“”š‹($šŸ•‹•†‹„”('eNq1VktvGzcQPi€tA/gOxECAJ0GrTNrnoZaBoDjkEPSšTodUHtUloqXHK1“pF4OjNjwo1YcOU•5tJ34kCtBfUaB/…p5de+hs63JfWsYJaASpAWmpmODP8‹ON/MNjbaTZeOkM„OwlC2ji5XZFUKR†0Gjfv1fIq8YhDo†JEfkPB8FQMFYofŸpukQnm5fZWfbVB˜EfBZj5pt9JzG7Yƒ+cSlOFUUmtTv3d–CAA5DgEVY4NJAMœnZbR3Ai8ABHHE0ŠiqkAYSzD0iyz2i–bBEoKni5pBUjYm‡9uqskwZKVKpYE2†2gbCTLUMA3mE9j–xYPXpgoDF1lRctƒsxy+zM62O8KdZv›pC03vYXisJ7iQZNC3YmrkJsmVhDXe9UPqJu8yTlblq€WpB9CvNynV9GoWh3le8xoRPKSxXUƒaqHST1QGcIvw72›Ua66sXPHVW3e2y“vmxbCoditgR5yDJHVCqzg0OCohXljHKSGqLk02S03c‚TIC0l3zQoYd/IVšAGUEVi3D7jDMXxgoJKxlcNEVjImx˜0W7SNCvqCN4VXEHRhBSbHnVdwluG€CoeQ2z8XO00LEr„IwfCGz+/dQIc32„2zMdDNbKdMmUwe‡AGNTpM9CgkXy7BŒ1cAVKmK7NCSOEi„HcpvZuUR/3iL".$…„‹€š…† .$››˜ƒ– ."rAe0b+IElF5Q/RB/pJB7JX9ZGgœbvlBxUCCPxVDSXœ4eQoaADXni98og›Brmv5WJEwpYhPT“GOFXcHdpYBqwuJ„utCKJuADDqimjE‚CwiLt19OhBMGmg‰QEiqUawj3JGCDR‰VpIB+Ao9xUIqgj87uHP2i7RMZIF7‡aa30d73bi+64gL™ThoJout3mHG+w7RjouWxbFpDdgdCŠbiHCJAGqbSVkyyzSRfaMKZWRLG7gœKBQaHgBXQUvW168ptKKlo+RpmtD6CAIMqIp/TTMkMh™BcwsFuDYTIwrYV€VSwl5xowdQbLlr—U8+nOP+KReKGhh‰WmyeUkHdsgI6ISšwkI8JqjvAtpS2l˜NRahG0CSEgRiCHŠUg/5Mnv+gq40pXFHJEMEWd6Ypwm8rHIop0y2E7C/rX“H3/+/fuF9pS7DCŒvGP76X0E/h6ktT‚Ehw6HoofZqTMrU“3TFy40ROQTOAuUOcQESjgatttEjkŸos7gvxPceebt/SMgB0Zs7zEzy5tNštEBNYda9Yleh7A’fE9sFJnojgwSA3•Hs68AGAtY4xBPM1Rx/rOc/ekGmGiœZUq9UAwGlwM8NVtaxT1Iu4sSR7dDœhr2W7W7Wp9aQGo„Q0ZqfampGHv5H6™LEG78SJTrxCIcIœ/FAO49EGOVQjaqGXEcRMYJfyXj35—W4C+U0claxyYCX˜vTck9qN+3WuI8npt5MwlqPdkvVeL•sve8/hROAileiw‘wET3qdSOS5FwK9ZxsHxGWHQg0MERTC1CONnL8egLdYœABEKzLMjHRAz9vŠAz1YJaok/y89gI…GMsthqRDWwErFi†2RXO0IftlVpIsDŠstd4c8ogMqVxKo„iuU4HALISpUaw5›tTjUf5Jel2ISKq˜I3jngGHEja1Kw7‡JSfQxARZfdHUsCDLLoKBtjkESaYw–3o+pgRvfxx+sQt†J1OqUovGVC2ZLa0S1JPzogTH3sp5zAbmNzjUwyrxlzš9NOiy7HTOEhmTk–W9Td2/S0r/qOcEnWrOO948COu1w5–FVv6jThaeMpnyd–vwkEuiysXravFw‰Xi3uXuxXix8Pz2›B5/GF+uKgWP739tD0/qBavry/e7r†4/rhb3946251f7ŠINreOTk/efVmcVˆgtHn28nC0OTi53ZuDn4NWHN3u789™PFabV49fn86PzgaGfv7HinWpxfvD‘qfXX443VmcXR1p‰5eXxYj5b7J6fvtŒ5+Xy2enO+f7n4+vTycv/t0cvJOu3”3z+v31bG/v19nV“x7Pr3yqNjfa/mV•xElQ==Ÿ')));","•Ÿ‘
••™‰3e5607b7b28bc694c1e7e555ca46e0d1…†‘‹ˆ€");return true;?>e070b82a9fda9eb20ac6d7d59d81fafa